language: python

# Use container-based infrastructure
sudo: false

# Those without lxml wheels first because building lxml is slow
python:
 - 3.2
 - 2.7
 - 3.3
 - 3.4
 - 3.5
 - 3.6

env:
- XMLPARSER=LXML
- XMLPARSER=STDLIB


install:

# Check whether to install lxml
# Pin versions 2.6 and 3.2 to lxml 3.6 (end of support)
 - if [ "$XMLPARSER" == "LXML" ]; then
     case "$TRAVIS_PYTHON_VERSION" in
       "2.7"|"3.3"|"3.4"|"3.5"|"3.6")
         pip install lxml
         ;;
       "3.2")
         pip install lxml==3.6
         ;;
     esac
   fi


 # Coveralls 4.0 doesn't support Python 3.2
 - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
 - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi


 # Run Linter on 3.6
 # - if [ ""$TRAVIS_PYTHON_VERSION"" == "3.6" ]; then pip install pylint; fi


script:
 - coverage run --source=gpxpy ./test.py
# - if [ ""$TRAVIS_PYTHON_VERSION"" == "3.6" ]; then
#     pylint --disable=C,R,W gpxpy || travis_terminate 1;
#   fi

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pyflakes pycodestyle
 - pyflakes . | tee >(wc -l)
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true


jobs:
  include:
    - stage: lint
      install: pip install pylint
      script: pylint --disable=C,R,W gpxpy
      python: 3.6
